// Aliases share one point opportunity; repetition never adds points.
export const roles = [
  {
    name: "Software Engineer Intern",
    short: "SWE",
    icon: "</>",
    subtitle: "Build & ship",
  },
  {
    name: "Data Analyst Intern",
    short: "DATA",
    icon: "▥",
    subtitle: "Find the signal",
  },
  {
    name: "Product / Tech Consultant",
    short: "CONSULTING",
    icon: "↗",
    subtitle: "Connect the dots",
  },
];
const keywordBanks = {
  "Software Engineer Intern": [
    ["javascript"],
    ["typescript"],
    ["python"],
    ["react"],
    ["node.js", "nodejs", "node js"],
    ["api", "apis", "rest", "restful"],
    ["database", "databases"],
    ["sql"],
    ["git", "github"],
    ["agile", "scrum"],
    ["html"],
    ["css"],
    ["frontend", "front-end"],
    ["backend", "back-end"],
    ["java"],
    ["c++"],
    ["algorithm", "algorithms"],
    ["data structure", "data structures"],
    ["debugging"],
    ["testing", "unit test", "unit tests"],
    ["docker"],
    ["linux", "unix"],
    ["ci/cd"],
  ],
  "Data Analyst Intern": [
    ["excel"],
    ["python"],
    ["sql"],
    ["tableau"],
    ["power bi", "powerbi"],
    ["analytics", "data analysis"],
    ["data visualization", "data visualisation"],
    ["statistical", "statistics"],
    ["regression"],
    ["machine learning"],
    ["data cleaning"],
    ["etl"],
    ["data warehouse"],
    ["r programming"],
    ["pandas"],
    ["numpy"],
    ["dashboard", "dashboards"],
    ["report", "reports"],
    ["kpi", "kpis"],
    ["business intelligence"],
    ["eda", "exploratory data analysis"],
    ["pivot table", "pivot tables"],
  ],
  "Product / Tech Consultant": [
    ["product management"],
    ["stakeholder", "stakeholders"],
    ["roadmap", "roadmaps"],
    ["user story", "user stories"],
    ["requirements"],
    ["wireframe", "wireframes"],
    ["prototype", "prototyping"],
    ["ux", "user experience"],
    ["market research"],
    ["competitive analysis"],
    ["strategy"],
    ["agile", "scrum"],
    ["sprint", "sprints"],
    ["cross-functional"],
    ["presentation", "presentations"],
    ["communication"],
    ["client", "clients"],
    ["consulting"],
    ["problem solving", "problem-solving"],
    ["kpi", "kpis", "metrics"],
    ["digital transformation"],
  ],
};
export default keywordBanks;
